import React, { useState, useEffect, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Eye, Edit, Trash2, Search, Filter } from "lucide-react";
import useAdminAuth from "../hooks/useAdminAuth";
import { fetchAdminProposals, deleteAdminProposal } from "../api/proposalApi";

const Proposals = () => {
  const navigate = useNavigate();
  const { hasPermission } = useAdminAuth();
  
  const [proposals, setProposals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchInput, setSearchInput] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");

  const canEdit = useMemo(() => hasPermission("Proposals", "edit"), [hasPermission]);
  const canDelete = useMemo(() => hasPermission("Proposals", "delete"), [hasPermission]);

  const loadProposals = async () => {
    try {
      setLoading(true);
      const data = await fetchAdminProposals(searchInput, statusFilter);
      setProposals(data);
    } catch (error) {
      toast.error("Failed to fetch proposals");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      loadProposals();
    }, 400);

    return () => clearTimeout(delayDebounceFn);
  }, [searchInput, statusFilter]);

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this proposal?")) {
      try {
        await deleteAdminProposal(id);
        toast.success("Proposal deleted successfully");
        loadProposals();
      } catch (error) {
        toast.error("Failed to delete proposal");
      }
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Pending": return "bg-amber-100 text-amber-700";
      case "Accepted": return "bg-emerald-100 text-emerald-700";
      case "Rejected": return "bg-red-100 text-red-700";
      default: return "bg-slate-100 text-slate-700";
    }
  };

  return (
    <div className="mx-auto w-full max-w-7xl flex flex-col p-2 sm:p-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
        <h1 className="text-xl font-bold text-slate-900">Generated Proposals</h1>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-3 mb-4 flex flex-col sm:flex-row justify-between items-center gap-3">
        <div className="flex w-full sm:w-auto relative">
          <div className="absolute inset-y-0 left-2.5 flex items-center pointer-events-none text-slate-400">
            <Search size={14} />
          </div>
          <input 
            type="text" 
            placeholder="Search ID, Title, Employee..." 
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            className="border border-slate-300 bg-white rounded-lg pl-8 pr-3 py-1.5 w-full sm:w-72 text-[12px] focus:outline-none focus:ring-2 focus:ring-teal-100 focus:border-teal-600 transition-all"
          />
        </div>
        
        <div className="w-full sm:w-auto flex items-center gap-2">
          <span className="text-[12px] font-medium text-slate-700 flex items-center gap-1"><Filter size={14}/> Status:</span>
          <select 
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="border border-slate-300 bg-white rounded-lg px-2 py-1.5 text-[12px] focus:outline-none focus:ring-2 focus:ring-teal-100 focus:border-teal-600 transition-all cursor-pointer"
          >
            <option value="All">All Proposals</option>
            <option value="Pending">Pending</option>
            <option value="Accepted">Accepted</option>
            <option value="Rejected">Rejected</option>
          </select>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-200">
            <thead className="bg-slate-50">
              <tr>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Proposal ID & Date</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Details</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Generated By</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Status</th>
                <th className="px-3 py-2.5 text-right text-[10px] font-bold text-slate-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan="5" className="px-3 py-6 text-center text-[12px] font-medium text-slate-500">Loading proposals...</td>
                </tr>
              ) : proposals.length === 0 ? (
                <tr>
                  <td colSpan="5" className="px-3 py-6 text-center text-[12px] font-medium text-slate-500">No proposals found matching criteria.</td>
                </tr>
              ) : (
                proposals.map((prop) => (
                  <tr key={prop._id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.proposalId}</div>
                      <div className="text-[10px] font-medium text-slate-500 mt-0.5">{new Date(prop.createdAt).toLocaleDateString()}</div>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.title}</div>
                      <div className="text-[10px] font-medium text-slate-500 mt-0.5">Cost: {prop.totalCost} • Until: {new Date(prop.validUntil).toLocaleDateString()}</div>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.createdBy || "Admin"}</div>
                      {prop.creatorEmployeeId && (
                        <div className="text-[10px] font-medium text-slate-500 mt-0.5">Emp ID: {prop.creatorEmployeeId}</div>
                      )}
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <span className={`px-2 py-1 inline-flex text-[10px] uppercase tracking-wider font-bold rounded-md ${getStatusColor(prop.status)}`}>
                        {prop.status}
                      </span>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap text-right text-[12px] font-semibold flex justify-end items-center gap-2">
                      <button 
                        onClick={() => navigate(`/admin/proposals/${prop._id}`)}
                        className="p-1 text-slate-500 hover:text-slate-900 hover:bg-slate-100 rounded-md transition-colors"
                        title="View Details"
                      >
                        <Eye size={14} />
                      </button>
                      
                      {canEdit && (
                        <button 
                          onClick={() => navigate(`/admin/proposals/edit/${prop._id}`)}
                          className="p-1 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded-md transition-colors"
                          title="Edit Proposal"
                        >
                          <Edit size={14} />
                        </button>
                      )}

                      {canDelete && (
                        <button 
                          onClick={() => handleDelete(prop._id)}
                          className="p-1 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-md transition-colors"
                          title="Delete Proposal"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Proposals;