import React, { useState, useEffect, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Eye, Edit, Trash2, Search, Filter, FileText, FileSignature, FolderPlus, CheckCircle2 } from "lucide-react";
import useAdminAuth from "../hooks/useAdminAuth";
import { fetchAdminProposals, deleteAdminProposal, updateProposalStatus } from "../api/proposalApi";

const QoutesProposals = () => {
  const navigate = useNavigate();
  const adminAuth = useAdminAuth();
  
  const [proposals, setProposals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchInput, setSearchInput] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");

  const canEdit = useMemo(() => {
    if (adminAuth && typeof adminAuth.hasPermission === "function") {
      return adminAuth.hasPermission("proposals", "edit");
    }
    return true;
  }, [adminAuth]);

  const canDelete = useMemo(() => {
    if (adminAuth && typeof adminAuth.hasPermission === "function") {
      return adminAuth.hasPermission("proposals", "delete");
    }
    return true;
  }, [adminAuth]);

  const loadProposals = async () => {
    try {
      setLoading(true);
      const data = await fetchAdminProposals(searchInput, statusFilter);
      setProposals(data);
    } catch (error) {
      toast.error("Failed to fetch proposals");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      loadProposals();
    }, 400);

    return () => clearTimeout(delayDebounceFn);
  }, [searchInput, statusFilter]);

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this proposal?")) {
      try {
        await deleteAdminProposal(id);
        toast.success("Proposal deleted successfully");
        loadProposals();
      } catch (error) {
        toast.error("Failed to delete proposal");
      }
    }
  };

  const handleStatusChange = async (id, newStatus) => {
    try {
      await updateProposalStatus(id, newStatus);
      toast.success("Status updated successfully");
      loadProposals();
    } catch (error) {
      toast.error("Failed to update status");
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Pending": return "bg-amber-100 text-amber-700";
      case "Accepted": return "bg-emerald-100 text-emerald-700";
      case "Rejected": return "bg-red-100 text-red-700";
      default: return "bg-slate-100 text-slate-700";
    }
  };
 
  return (
    <div className="mx-auto w-full max-w-7xl flex flex-col p-2 sm:p-4">
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-3 mb-4 flex flex-col sm:flex-row justify-between items-center gap-3">
        <div className="flex w-full sm:w-auto relative">
          <div className="absolute inset-y-0 left-2.5 flex items-center pointer-events-none text-slate-400">
            <Search size={14} />
          </div>
          <input 
            type="text" 
            placeholder="Search ID, Title, Employee..." 
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            className="border border-slate-300 bg-white rounded-lg pl-8 pr-3 py-1.5 w-full sm:w-72 text-[12px] focus:outline-none focus:ring-2 focus:ring-teal-100 focus:border-teal-600 transition-all"
          />
        </div>
        
        <div className="w-full sm:w-auto flex items-center gap-2">
          <span className="text-[12px] font-medium text-slate-700 flex items-center gap-1"><Filter size={14}/> Status:</span>
          <select 
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="border border-slate-300 bg-white rounded-lg px-2 py-1.5 text-[12px] focus:outline-none focus:ring-2 focus:ring-teal-100 focus:border-teal-600 transition-all cursor-pointer"
          >
            <option value="All">All Proposals</option>
            <option value="Pending">Pending</option>
            <option value="Accepted">Accepted</option>
            <option value="Rejected">Rejected</option>
          </select>
        </div>
      </div> 

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-200">
            <thead className="bg-slate-50">
              <tr>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Proposal Info</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Quote Reference</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Generated By</th>
                <th className="px-3 py-2.5 text-left text-[10px] font-bold text-slate-500 uppercase tracking-wider">Status</th>
                <th className="px-3 py-2.5 text-right text-[10px] font-bold text-slate-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan="5" className="px-3 py-6 text-center text-[12px] font-medium text-slate-500">Loading proposals...</td>
                </tr>
              ) : proposals.length === 0 ? (
                <tr>
                  <td colSpan="5" className="px-3 py-6 text-center text-[12px] font-medium text-slate-500">No proposals found matching criteria.</td>
                </tr>
              ) : (
                proposals.map((prop) => (
                  <tr key={prop._id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.proposalId}</div>
                      <div className="text-[10px] font-medium text-slate-500 mt-0.5">{prop.title}</div>
                      <div className="text-[10px] font-medium text-teal-700 mt-0.5">{prop.totalCost}</div>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.quote?.quoteId || "N/A"}</div>
                      <div className="text-[10px] font-medium text-slate-500 mt-0.5">{prop.quote?.projectTitle || "Unknown"}</div>
                      <div className="text-[10px] font-medium text-slate-500 mt-0.5">{prop.quote?.fullName || ""}</div>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <div className="text-[12px] font-bold text-slate-900">{prop.createdBy || "Admin"}</div>
                      {prop.creatorEmployeeId && (
                        <div className="text-[10px] font-medium text-slate-500 mt-0.5">Emp ID: {prop.creatorEmployeeId}</div>
                      )}
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap">
                      <select
                        value={prop.status}
                        onChange={(e) => handleStatusChange(prop._id, e.target.value)}
                        disabled={!canEdit}
                        className={`px-2 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider outline-none cursor-pointer border border-transparent hover:border-slate-300 transition-all ${getStatusColor(prop.status)} ${!canEdit && 'opacity-70 cursor-not-allowed'}`}
                      >
                        <option value="Pending">Pending</option>
                        <option value="Accepted">Accepted</option>
                        <option value="Rejected">Rejected</option>
                      </select>
                    </td>
                    <td className="px-3 py-2.5 whitespace-nowrap text-right text-[12px] font-semibold flex justify-end items-center gap-1.5">
                      
                      {prop.status === "Accepted" && canEdit && (
                        prop.hasProject ? (
                          <span className="inline-flex items-center gap-1 px-2 py-1 bg-emerald-50 text-emerald-700 text-[10px] font-bold rounded-md border border-emerald-200">
                            <CheckCircle2 size={12} /> Project Created
                          </span>
                        ) : (
                          <button 
                            onClick={() => navigate(`/admin/clientprojects/create/${prop._id}`)}
                            className="p-1.5 text-orange-500 hover:bg-orange-50 rounded-md transition-colors"
                            title="Create Project"
                          >
                            <FolderPlus size={14} />
                          </button>
                        )
                      )}

                      <button 
                        onClick={() => navigate(`/admin/proposals/${prop._id}`)}
                        className="p-1.5 text-slate-500 hover:bg-slate-100 hover:text-slate-900 rounded-md transition-colors"
                        title="View Proposal Details"
                      >
                        <Eye size={14} />
                      </button>

                      {canEdit && (
                        <button 
                          onClick={() => navigate(`/admin/proposals/edit/${prop._id}`)}
                          className="p-1.5 text-blue-500 hover:bg-blue-50 rounded-md transition-colors"
                          title="Edit Proposal"
                        >
                          <Edit size={14} />
                        </button>
                      )}

                      {canDelete && (
                        <button 
                          onClick={() => handleDelete(prop._id)}
                          className="p-1.5 text-red-500 hover:bg-red-50 rounded-md transition-colors"
                          title="Delete Proposal"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}

                      {canEdit && (
                        <>
                          <div className="w-px h-4 bg-slate-300 mx-1"></div>
                          <button 
                            onClick={() => navigate(`/admin/quotes/edit/${prop.quote?._id || prop.quote}`)}
                            className="p-1.5 text-indigo-500 hover:bg-indigo-50 rounded-md transition-colors"
                            title="Edit Original Quote"
                          >
                            <FileSignature size={14} />
                          </button>
                        </>
                      )}

                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default QoutesProposals;